---
- name: Setup | add openstack user
  community.rabbitmq.rabbitmq_user:
    user: openstack
    password: "{{ rabbitmq_openstack_password }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    force: true
  become: true
  delegate_to: "{{ groups['rabbitmq'][0] }}"
  run_once: true

- name: Setup | enable plugins
  community.rabbitmq.rabbitmq_plugin:
    names: "{{ rabbitmq_plugins }}"
    state: enabled
  become: true

#- name: Setup | set the HA policy
#  community.rabbitmq.rabbitmq_policy:
#    name: HA
#    pattern: "^(?!amq.).*"
#    tags:
#      ha-mode: exactly
#      ha-params: 2
#      ha-syncmode: automatic
#  become: true
#  delegate_to: "{{ groups['rabbitmq'][0] }}"
#  run_once: true
...
