---
- name: Start | import common tasks
  tags:
    - rabbitmq
    - pbos-infra
  ansible.builtin.import_tasks: "common.yml"

- name: Start | get bootstrap server
  tags:
    - rabbitmq
    - pbos-infra
  ansible.builtin.lineinfile:
    path: "{{ bootstrap_file }}"
    line: "['rabbit@{{ inventory_hostname }}']."
    state: present
  check_mode: true
  become: true
  register: safe_to_bootstrap

- name: Start | get the server that can bootstrap safely
  tags:
    - rabbitmq
    - pbos-infra
  set_fact:
    bootstrap: "{{ safe_to_bootstrap.changed | ternary(false, true) }}"

- name: Start | show bootstrap
  tags:
    - rabbitmq
    - pbos-infra
  debug:
    msg: "{{ bootstrap }}"

- name: Start | start service on bootstrap server
  tags:
    - rabbitmq
    - pbos-infra
  block:
    - name: start service
      ansible.builtin.service:
        name: "{{ item }}"
        state: "started"
      become: true
      register: start_service
      failed_when: start_service.failed
      loop: "{{ systemd_service_name }}"
      when: bootstrap
    - name: wait until port is opened
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: "{{ rabbitmq_port }}"
        delay: 5
        sleep: 2
        timeout: 20
        state: started
      when: bootstrap

- name: Start | start service on other server
  tags:
    - rabbitmq
    - pbos-infra
  block:
    - name: start service
      ansible.builtin.service:
        name: "{{ item }}"
        state: "started"
      become: true
      register: start_service
      failed_when: start_service.failed
      loop: "{{ systemd_service_name }}"
      when: not bootstrap
    - name: wait until port is opened
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: "{{ rabbitmq_port }}"
        sleep: 2
        timeout: 10
        state: started
      when: not bootstrap
...
