---
- name: Stop | import common tasks
  tags: rabbitmq
  ansible.builtin.import_tasks: "common.yml"

- name: Stop | stop service
  tags: rabbitmq
  block:
    - name: stop service
      ansible.builtin.service:
        name: "{{ item }}"
        state: "stopped"
      become: true
      register: stop_service
      failed_when: stop_service.failed
      loop: "{{ systemd_service_name }}"
    - name: wait until port is closed.
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: "{{ rabbitmq_port }}"
        sleep: 2
        timeout: 10
        state: stopped
...
