---
- name: Stop | include default variables
  tags: rabbitmq
  ansible.builtin.include_vars: "../vars/main.yml"

- name: Stop | include os specific variables
  tags: rabbitmq
  ansible.builtin.include_vars: "{{ lookup('first_found', _params) }}"
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "../vars"

- name: stop service
  tags: rabbitmq
  block:
    - name: stop service
      ansible.builtin.service:
        name: "{{ item }}"
        state: "stopped"
      become: true
      register: stop_service
      failed_when: stop_service.failed
      loop: "{{ systemd_service_name }}"
    - name: wait until port is closed.
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: "{{ rabbitmq_port }}"
        sleep: 2
        timeout: 10
        state: stopped
...
